name: Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configurar variáveis de ambiente
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
          TESTE: ${{ secrets.NOVO_TESTE }}
        run: echo "O segredo é $SERVICE_KEY"
        
      - name: Checkout do código
        uses: actions/checkout@v3
